services:
  localstack:
    image: localstack/localstack:4.1.1
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    env_file:
      - ../.env
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
      EXTRA_CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,https://sfitz42.github.io"
      EXTRA_CORS_ALLOWED_HEADERS: 'X-Amzn-Query-Mode'
    volumes:
      - ./start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
